// `AnalyzeOptions` is defined (and hand-kept in sync) by the napi-rs generated
// `native.d.ts`, so re-export it here rather than duplicating it — this keeps the
// public camelCase option names (`root`, `config`, `includeTypeEdges`, `noCache`)
// derived from a single source of truth and avoids drift.
import type { AnalyzeOptions } from './native'
export type { AnalyzeOptions }

/**
 * Shape of the report returned by `analyze()`.
 *
 * `native.d.ts` (generated by napi-rs) declares `analyze` to return
 * `Promise<AnalysisReport>` but does not define the type itself (the report is
 * serialized from Rust as `serde_json::Value`), so it is declared here and kept
 * in sync with `unstave_report::build_report`.
 */
export interface AnalysisReport {
  schemaVersion: 2
  workspace: { root: string; kind: string; packages: unknown[] }
  summary: {
    filesAnalyzed: number
    modules: number
    edges: number
    cycles: number
    classifiedBarrels: number
  }
  amplification: {
    barrels: Array<{
      barrel: string
      /** Always a finite number — never `null`, never `Infinity`. */
      maxAmplification: number
      totalExcess: number
    }>
  }
  [key: string]: unknown
}

export function analyze(options: AnalyzeOptions): Promise<AnalysisReport>

/**
 * Render a report to one self-contained HTML page.
 *
 * `maxNodes` (default 150) is the point past which the graph collapses directories
 * into single nodes, matching the CLI's `--max-nodes`. Raising it past a few hundred
 * makes the layout slow to settle on large workspaces.
 */
export function renderHtml(report: AnalysisReport, maxNodes?: number): Promise<string>
